### ISSUE TITLE
Doesn't seem to download anything

### ISSUE THREAD

**Issue by praeludiumOrbis** [WhosMyName/ProxLoadMe#4]
By the way, thank you very much for fixing my previous issues.
```
E:\Program Files\ProxLoadMe>python ProxLoadMe.py
2020-07-12 17:11:16,128 | ERROR | ProxLoadMe plme.main 17904 16248 |           init_preps() - Line 80 | 'NoneType' object is not subscriptable
Traceback (most recent call last):
  File "ProxLoadMe.py", line 76, in init_preps
    url = soup.find("form")["action"]
TypeError: 'NoneType' object is not subscriptable
2020-07-12 17:11:16,130 | INFO | ProxLoadMe plme.main 17904 16248 |           init_preps() - Line 82 | Recommended URL-Format would be: http://proxer.me/info/277/

Please enter the URL of the Anime you want to download: https://proxer.me/info/1874
Please enter the Number of the first Episode you want: 1
Please enter the Number of the last Episode you want: 22
2020-07-12 17:11:29,937 | INFO | ProxLoadMe plme.main 17904 16248 |           init_preps() - Line 119 | Creating Worker for Episode 1
2020-07-12 17:11:29,939 | INFO | ProxLoadMe plme.main 17904 16248 |           init_preps() - Line 119 | Creating Worker for Episode 2
2020-07-12 17:11:29,941 | INFO | ProxLoadMe plme.main 17904 16248 |           init_preps() - Line 119 | Creating Worker for Episode 3
2020-07-12 17:11:29,943 | INFO | ProxLoadMe plme.main 17904 16248 |           init_preps() - Line 119 | Creating Worker for Episode 4
2020-07-12 17:11:29,946 | INFO | ProxLoadMe plme.main 17904 16248 |           init_preps() - Line 119 | Creating Worker for Episode 5
2020-07-12 17:11:29,948 | INFO | ProxLoadMe plme.main 17904 16248 |           init_preps() - Line 119 | Creating Worker for Episode 6
2020-07-12 17:11:29,950 | INFO | ProxLoadMe plme.main 17904 16248 |           init_preps() - Line 119 | Creating Worker for Episode 7
2020-07-12 17:11:29,950 | INFO | ProxLoadMe plme.main 17904 16248 |           init_preps() - Line 119 | Creating Worker for Episode 8
2020-07-12 17:11:29,951 | INFO | ProxLoadMe plme.main 17904 16248 |           init_preps() - Line 119 | Creating Worker for Episode 9
2020-07-12 17:11:29,951 | INFO | ProxLoadMe plme.main 17904 16248 |           init_preps() - Line 119 | Creating Worker for Episode 10
2020-07-12 17:11:29,952 | INFO | ProxLoadMe plme.main 17904 16248 |           init_preps() - Line 119 | Creating Worker for Episode 11
2020-07-12 17:11:29,953 | INFO | ProxLoadMe plme.main 17904 16248 |           init_preps() - Line 119 | Creating Worker for Episode 12
2020-07-12 17:11:29,954 | INFO | ProxLoadMe plme.main 17904 16248 |           init_preps() - Line 119 | Creating Worker for Episode 13
2020-07-12 17:11:29,954 | INFO | ProxLoadMe plme.main 17904 16248 |           init_preps() - Line 119 | Creating Worker for Episode 14
2020-07-12 17:11:29,954 | INFO | ProxLoadMe plme.main 17904 16248 |           init_preps() - Line 119 | Creating Worker for Episode 15
2020-07-12 17:11:29,955 | INFO | ProxLoadMe plme.main 17904 16248 |           init_preps() - Line 119 | Creating Worker for Episode 16
2020-07-12 17:11:29,955 | INFO | ProxLoadMe plme.main 17904 16248 |           init_preps() - Line 119 | Creating Worker for Episode 17
2020-07-12 17:11:29,956 | INFO | ProxLoadMe plme.main 17904 16248 |           init_preps() - Line 119 | Creating Worker for Episode 18
2020-07-12 17:11:29,956 | INFO | ProxLoadMe plme.main 17904 16248 |           init_preps() - Line 119 | Creating Worker for Episode 19
2020-07-12 17:11:29,956 | INFO | ProxLoadMe plme.main 17904 16248 |           init_preps() - Line 119 | Creating Worker for Episode 20
2020-07-12 17:11:29,957 | INFO | ProxLoadMe plme.main 17904 16248 |           init_preps() - Line 119 | Creating Worker for Episode 21
2020-07-12 17:11:29,960 | INFO | ProxLoadMe plme.main 17904 16248 |           init_preps() - Line 119 | Creating Worker for Episode 22
2020-07-12 17:11:30,076 | INFO | ProxLoadMe plme.main 17904 16248 |           init_preps() - Line 126 | Worker for Episode 22 returned: True
2020-07-12 17:11:30,098 | INFO | ProxLoadMe plme.main 17904 16248 |           init_preps() - Line 126 | Worker for Episode 22 returned: True
2020-07-12 17:11:30,135 | INFO | ProxLoadMe plme.main 17904 16248 |           init_preps() - Line 126 | Worker for Episode 22 returned: True
2020-07-12 17:11:30,149 | INFO | ProxLoadMe plme.main 17904 16248 |           init_preps() - Line 126 | Worker for Episode 22 returned: True
2020-07-12 17:11:30,196 | INFO | ProxLoadMe plme.main 17904 16248 |           init_preps() - Line 126 | Worker for Episode 22 returned: True
2020-07-12 17:11:30,262 | INFO | ProxLoadMe plme.main 17904 16248 |           init_preps() - Line 126 | Worker for Episode 22 returned: True
2020-07-12 17:11:30,283 | INFO | ProxLoadMe plme.main 17904 16248 |           init_preps() - Line 126 | Worker for Episode 22 returned: True
2020-07-12 17:11:30,305 | INFO | ProxLoadMe plme.main 17904 16248 |           init_preps() - Line 126 | Worker for Episode 22 returned: True
2020-07-12 17:11:30,325 | INFO | ProxLoadMe plme.main 17904 16248 |           init_preps() - Line 126 | Worker for Episode 22 returned: True
2020-07-12 17:11:30,404 | INFO | ProxLoadMe plme.main 17904 16248 |           init_preps() - Line 126 | Worker for Episode 22 returned: True
2020-07-12 17:11:30,456 | INFO | ProxLoadMe plme.main 17904 16248 |           init_preps() - Line 126 | Worker for Episode 22 returned: True
2020-07-12 17:11:30,478 | INFO | ProxLoadMe plme.main 17904 16248 |           init_preps() - Line 126 | Worker for Episode 22 returned: True
2020-07-12 17:11:30,494 | INFO | ProxLoadMe plme.main 17904 16248 |           init_preps() - Line 126 | Worker for Episode 22 returned: True
2020-07-12 17:11:30,512 | INFO | ProxLoadMe plme.main 17904 16248 |           init_preps() - Line 126 | Worker for Episode 22 returned: True
2020-07-12 17:11:30,582 | INFO | ProxLoadMe plme.main 17904 16248 |           init_preps() - Line 126 | Worker for Episode 22 returned: True
2020-07-12 17:11:30,605 | INFO | ProxLoadMe plme.main 17904 16248 |           init_preps() - Line 126 | Worker for Episode 22 returned: True
2020-07-12 17:11:30,627 | INFO | ProxLoadMe plme.main 17904 16248 |           init_preps() - Line 126 | Worker for Episode 22 returned: True
2020-07-12 17:11:30,652 | INFO | ProxLoadMe plme.main 17904 16248 |           init_preps() - Line 126 | Worker for Episode 22 returned: True
2020-07-12 17:11:30,675 | INFO | ProxLoadMe plme.main 17904 16248 |           init_preps() - Line 126 | Worker for Episode 22 returned: True
2020-07-12 17:11:30,753 | INFO | ProxLoadMe plme.main 17904 16248 |           init_preps() - Line 126 | Worker for Episode 22 returned: True
2020-07-12 17:11:30,771 | INFO | ProxLoadMe plme.main 17904 16248 |           init_preps() - Line 126 | Worker for Episode 22 returned: True
2020-07-12 17:11:30,784 | INFO | ProxLoadMe plme.main 17904 16248 |           init_preps() - Line 126 | Worker for Episode 22 returned: True
```

**Comment by WhosMyName** [comment]
Hey @myangelaku,

this one is going to be a pretty tough nut.
It says:
```python
2020-07-12 17:11:16,128 | ERROR | ProxLoadMe plme.main 17904 16248 |           init_preps() - Line 80 | 'NoneType' object is not subscriptable
Traceback (most recent call last):
  File "ProxLoadMe.py", line 76, in init_preps
    url = soup.find("form")["action"]
```
I'm not using any "NoneType" object leading to the conclusion, that something went wrong during the creation of the BeautifulSoup object

```python
strainer = SoupStrainer(id="loginBubble")
soup = BeautifulSoup(resp.content, "html.parser", parse_only=strainer) # <-----
url = soup.find("form")["action"]
```
There two scenarios that come to my mind:
* something went wrong during the request (corrupted/incorrect data)
* the strainer couldn't process the data (incorrect data)
* anything that could stop an object from being created

Just tried the script and it's working just finesgate;
If the Issue is reoccurring, I'd recommend either 
* updating/reinstalling BeautifulSoup
* checking the site manually 
* if you're feeling lucky: using a smart editor (VS Code, Sublime, Atom, etc..) to debug the script at Line 73
![Untitled](https://user-images.githubusercontent.com/11244648/87347480-96babf80-c553-11ea-9721-8ee7fb1e3cb5.png)

I'm sorry I couldn't be of much help, so I'll leave this open for you to report findings (???)
And great thanks for reporting Issues <3

**Comment by praeludiumOrbis** [comment]
> Just tried the script and it's working just finesgate;
👀 

> updating/reinstalling BeautifulSoup
Did that and it works perfect c: 
Thanks for the amazing script!

Also; I know this doesn't belong here, but I'd appreciate some kind of progress bar ^^
